// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvhj1Chn1Y4V4pEae7kDfrm_Ydee75-s',
    appId: '1:683442076958:web:67dfd89937d62794bd1d0f',
    messagingSenderId: '683442076958',
    projectId: 'park-me-8e6ee',
    authDomain: 'park-me-8e6ee.firebaseapp.com',
    storageBucket: 'park-me-8e6ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKNEFF5umW7kqU3RWO2tx5HnejzkZzR8I',
    appId: '1:683442076958:android:55ddd4429c9d2160bd1d0f',
    messagingSenderId: '683442076958',
    projectId: 'park-me-8e6ee',
    storageBucket: 'park-me-8e6ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9OA1hYph6txxFtZKUJrD3Wc-fQsceQNA',
    appId: '1:683442076958:ios:e9685ca71e7dd70ebd1d0f',
    messagingSenderId: '683442076958',
    projectId: 'park-me-8e6ee',
    storageBucket: 'park-me-8e6ee.appspot.com',
    iosBundleId: 'com.example.parkme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9OA1hYph6txxFtZKUJrD3Wc-fQsceQNA',
    appId: '1:683442076958:ios:eb64fc1df6e00132bd1d0f',
    messagingSenderId: '683442076958',
    projectId: 'park-me-8e6ee',
    storageBucket: 'park-me-8e6ee.appspot.com',
    iosBundleId: 'com.example.parkme.RunnerTests',
  );
}
